timeout: "1200s"

substitutions:
  _REGION: us-central1
  _REPO: bva-api
  _SERVICE: bva-api

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:latest'

steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:latest', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:latest']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run','deploy','$_SERVICE',
        '--image','$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:latest',
        '--region','$_REGION',
        '--allow-unauthenticated'
      ]